name: Build Backend

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # run every Sunday at 00:00 UTC just to make sure the image is up to date
    - cron:  '0 0 * * 0'
  workflow_dispatch:
  push:
    branches: develop

env:
  CONTAINER_NAME: docker-cron-curl
  node_version: 21

jobs:
  build-backend:
    runs-on: 
      - ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: .

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Backend 
        run: |
          docker build --no-cache -t ${CONTAINER_NAME}:latest .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DH_USERNAME }}
          password: ${{ secrets.DH_TOKEN }}

      - name: Push to Docker Hub
        run: |
          echo "::group::Tag"
          echo "::debug::Tag the image with the latest tag"
          docker tag ${CONTAINER_NAME}:latest docker.io/${GITHUB_REPOSITORY_OWNER}/${CONTAINER_NAME}:latest
          echo "::endgroup::"

          echo "::group::Push"
          echo "::debug::Push the image to Github Container Registry"
          docker push docker.io/${GITHUB_REPOSITORY_OWNER}/${CONTAINER_NAME}:latest
          echo "::endgroup::"

